buffy:
  env:
    bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] %>
    gh_access_token: <%= ENV['BUFFY_GH_ACCESS_TOKEN'] %>
    gh_secret_token: <%= ENV['BUFFY_GH_SECRET_TOKEN'] %>
    reviewers_host_url: <%= ENV['REVIEWERS_HOST_URL'] %>
    reviewers_api_token: <%= ENV['REVIEWERS_API_TOKEN'] %>
  teams:
    editors: 1474888
    eics: 1415509
  responders:
    help:
      - commands:
          help_command: commands
      - help:
          help_command: help
          hidden: true
    whedon:
    thanks:
      hidden: true
    reviewers_list:
      only:
        - editors
        - eics
    assign_editor:
      only:
        - editors
        - eics
    remove_editor:
      only:
        - editors
        - eics
      no_editor_text: "TBD"
    add_remove_assignee:
      only:
        - editors
        - eics
    list_team_members:
      command: list editors
      description: "List all ReScience C Associate Editors"
      team_id: 1474888
      heading: Current ReScience C editors
    set_value:
      - version:
          only:
            - editors
            - eics
          sample_value: "v1.0.0"
      - archive:
          only:
            - editors
            - eics
          sample_value: "10.21105/joss.12345"
    close_issue_command:
      only:
        - editors
        - eics
      command: reject
      add_labels:
        - rejected
