buffy:
  env:
    bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] %>
    gh_access_token: <%= ENV['BUFFY_GH_ACCESS_TOKEN'] %>
    gh_secret_token: <%= ENV['BUFFY_GH_SECRET_TOKEN'] %>
  teams:
    editors: 2009411
  responders:
    help:
    help:
      help_command: commands
    list_of_values:
      - reviewers:
          only: editors
          if:
            role_assigned: editor
          sample_value: "@username"
          add_as_assignee: true
    assign_editor:
      only: editors
    remove_editor:
      only: editors
    set_value:
      - version:
          only: editors
          sample_value: "v1.0.0"
      - archive:
          only: editors
          sample_value: "10.21105/zenodo.12345"
