buffy:
  env:
    bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] %>
    gh_access_token: <%= ENV['BUFFY_GH_ACCESS_TOKEN'] %>
    gh_secret_token: <%= ENV['BUFFY_GH_SECRET_TOKEN'] %>
  teams:
    editors: aliadalabs/editors
    eics: aliadalabs/editors
  responders:
    help:
      help_command: commands
    list_of_values:
      - reviewers:
          only: editors
          if:
            role_assigned: editor
            reject_msg: "Can't add reviewers: There is no editor assigned yet"
          sample_value: "@username"
          add_as_assignee: true
    list_team_members:
      command: list editors
      team_id: aliadalabs/editors
      heading: List of Test-JOSS editors
      description: "Get a list of all editors's GitHub handles"
    assign_editor:
      only: editors
      external_call:
        url: "https://test.joss.theoj.org/papers/api_assign_editor"
        method: post
        query_params:
          secret: <%= ENV['JOSS_TEST_SECRET'] %>
        mapping:
          id: issue_id
          editor: editor
        silent: true
    remove_editor:
      only: editors
    check_references:
    repo_checks:
    reviewer_checklist_comment:
      template_file: reviewer_checklist.md
      data_from_issue:
        - target-repository
        - author-handle
    set_value:
      - version:
          only: editors
          sample_value: "v1.0.0"
      - archive:
          only: editors
          sample_value: "10.21105/zenodo.12345"
    external_service:
      - reject:
          only: eics
          command: reject
          description: "Reject paper"
          url: "https://test.joss.theoj.org/papers/api_reject"
          query_params:
            secret: <%= ENV['JOSS_TEST_SECRET'] %>
          mapping:
            id: issue_id
          add_labels:
            - rejected
          success_msg: "Paper rejected."
          error_msg: "There was a problem rejecting the paper."
          close: true
      - withdraw:
          only: eics
          command: withdraw
          description: "Withdraw paper"
          url: "https://test.joss.theoj.org/papers/api_withdraw"
          query_params:
            secret: <%= ENV['JOSS_TEST_SECRET'] %>
          mapping:
            id: issue_id
          add_labels:
            - withdrawn
          success_msg: "Paper withdrawn."
          error_msg: "There was a problem withdrawing the paper."
          close: true
      - invite_editor:
          only: eics
          command: "invite @(.*) as editor"
          description: "Invite an editor to edit a submission (sending them an email)"
          url: "https://test.joss.theoj.org/papers/api_editor_invite"
          query_params:
            secret: <%= ENV['JOSS_TEST_SECRET'] %>
          mapping:
            id: issue_id
            editor: match_data_1
          success_msg: Invitation to edit this submission sent!
          error_msg: "There was a problem inviting the user to edit this submission."
    github_action:
      - draft_paper:
          command: generate pdf
          workflow_repo: openjournals/joss-papers-testing
          workflow_name: draft-paper.yml
          workflow_ref: master
          description: Generates the pdf paper
          message: "Attempting PDF compilation. Reticulating splines etc..."
          data_from_issue:
            - branch
            - target-repository
            - issue_id
          mapping:
            repository_url: target-repository
    basic_command:
      - query_scope:
          only: editors
          command: query scope
          add_labels:
            - query-scope
          message: "Submission flagged for editorial review."
      - list_reviewers:
          command: list reviewers
          template_file: reviewers_list.md
    welcome:
      if:
        title: "^\\[PRE REVIEW\\]:"
      template_file: pre-review_welcome.md
      check_references:
      repo_checks:
